[project]
name = "dragonseeker"
version = "0.1.0"
description = "Dragonseeker - A social deduction party game"
requires-python = ">=3.13,<3.14"
dependencies = [
    "fastapi[standard]~=0.118.0",
]